# Generated by Django 5.0.2 on 2024-03-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='skills.skill'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
