# Generated by Django 5.0.2 on 2024-03-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('teams', '0001_initial'),
        ('users', '0003_user_сontact_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skills.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='сontact_information',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Contact information'),
        ),
    ]
